CREATE TABLE Book (
    BookID CHAR(10) NOT NULL,
    LessorID CHAR(10) NOT NULL,
    Tagline VARCHAR(500),
    Status BOOLEAN DEFAULT 0 NOT NULL,
    B_name VARCHAR(100) NOT NULL,
    ISBN INT(13),
    Full_price DECIMAL(10, 2),
    P_time INT(2),
    P_year INT(4),
    Publisher VARCHAR(100),
    Datebook DATE NOT NULL,
    RentPricePerDay INT(4) NOT NULL,
    SecurityDeposit INT(5) NOT NULL,
    Cost INT(5),
    Status_lo VARCHAR(50),
    Logic_com VARCHAR(100),
    StartDate DATE,
    EndDate DATE,
    TenantID VARCHAR(10),
    CID VARCHAR(2) NOT NULL,
    PRIMARY KEY (BookID, LessorID),
    FOREIGN KEY (LessorID) REFERENCES Member(MemberID),
    FOREIGN KEY (TenantID) REFERENCES Member(MemberID),
    FOREIGN KEY (CID) REFERENCES Category(CID)
);
